namespace Mutate4CSharp.Tests;

public sealed class ScopeRoundFourRegressionTests : IDisposable
{
    private readonly SnapshotTestRepository _repository = new();

    [Fact]
    public async Task DeletedHeaderGeneratedSourcePublishesOnlyGeneratedExclusion()
    {
        PrepareConfiguredRepository("// <auto-generated/>\nclass Generated { int Value() => 1; }\n");
        File.Delete(Path.Combine(_repository.Root, "src/App/Generated.cs"));

        var first = await PlanGitAsync();
        var second = await PlanGitAsync();

        var exclusion = Assert.Single(first.Exclusions);
        Assert.Equal("src/App/Generated.cs", exclusion.Path);
        Assert.Equal("GENERATED_SOURCE", exclusion.ReasonCode);
        Assert.False(exclusion.Overridden);
        Assert.Empty(first.Files);
        Assert.Empty(first.ProjectUnits);
        Assert.DoesNotContain(first.Reasons, reason => reason.Code is "COMPILE_ITEM_REMOVED" or
            "REMOVAL_DEPENDENCY_RISK" or "UNMAPPED_PROJECT");
        Assert.Contains(first.Reasons, reason => reason.Code == "NO_APPLICABLE_PRODUCTION_CHANGES");
        Assert.True(first.IsComplete);
        Assert.Equal(PlanValue(first), PlanValue(second));
        AssertPublishable(first, "deleted-header-generated");
    }

    [Fact]
    public async Task DeletedProductionSourceRetainsRemovalAndProjectExpansion()
    {
        PrepareConfiguredRepository("class Production { int Value() => 1; }\n");
        File.Delete(Path.Combine(_repository.Root, "src/App/Generated.cs"));

        var plan = await PlanGitAsync();

        Assert.Empty(plan.Exclusions);
        var file = Assert.Single(plan.Files);
        Assert.Equal("src/App/Generated.cs", file.Path);
        Assert.NotEmpty(file.Removals);
        Assert.True(file.RequiresProjectExpansion);
        Assert.Contains(file.Reasons, reason => reason.Code == "COMPILE_ITEM_REMOVED");
        Assert.Contains(plan.ProjectUnits, unit => unit.Project == "src/App/App.csproj" &&
            unit.Expansion == "FULL_PROJECT");
        Assert.DoesNotContain(plan.Reasons, reason => reason.Code == "NO_APPLICABLE_PRODUCTION_CHANGES");
        Assert.True(plan.IsComplete);
        AssertPublishable(plan, "deleted-production");
    }

    [Fact]
    public async Task DeletedHeaderGeneratedSourceIsAdmittedWhenOverrideEnabled()
    {
        PrepareConfiguredRepository("// <auto-generated/>\nclass Generated { int Value() => 1; }\n",
            includeGenerated: true);
        File.Delete(Path.Combine(_repository.Root, "src/App/Generated.cs"));

        var plan = await PlanGitAsync();

        Assert.Contains(plan.Exclusions, item => item.Path == "src/App/Generated.cs" &&
            item.ReasonCode == "GENERATED_SOURCE" && item.Overridden);
        var file = Assert.Single(plan.Files);
        Assert.NotEmpty(file.Removals);
        Assert.True(file.RequiresProjectExpansion);
        Assert.Contains(plan.ProjectUnits, unit => unit.Project == "src/App/App.csproj" &&
            unit.Expansion == "FULL_PROJECT");
        Assert.DoesNotContain(plan.Reasons, reason => reason.Code == "NO_APPLICABLE_PRODUCTION_CHANGES");
        Assert.True(plan.IsComplete);
        AssertPublishable(plan, "deleted-generated-override");
    }

    private void PrepareConfiguredRepository(string source, bool includeGenerated = false)
    {
        _repository.WriteText("src/App/App.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\" />\n");
        _repository.WriteText("tests/App.Tests/App.Tests.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk\" />\n");
        _repository.WriteText("src/App/Generated.cs", source);
        _repository.WriteText("mutate4csharp.json", $$"""
            { "version": 1, "includeGenerated": {{includeGenerated.ToString().ToLowerInvariant()}},
              "projects": [
              { "project": "src/App/App.csproj", "tests": ["tests/App.Tests/App.Tests.csproj"] }
            ] }
            """);
        _repository.Git("add", ".");
        _repository.Git("commit", "-m", "base");
    }

    private async Task<ScopePlan> PlanGitAsync()
    {
        await using var snapshot = await SnapshotCapture.CaptureAsync(_repository.Root, "HEAD", [],
            SnapshotCaptureOptions.Default, CancellationToken.None);
        return await ScopePlanner.PlanGitAsync(snapshot, CancellationToken.None);
    }

    private static void AssertPublishable(ScopePlan plan, string runId)
    {
        var report = EvaluationReport.CreateSynthetic(EvaluationOutcome.Incomplete, runId, "TEST_FIXTURE")
            with { ScopePlan = plan, Selection = new("base", "HEAD", []) };
        Assert.NotEmpty(ReportWriter.Serialize(report));
    }

    private static string PlanValue(ScopePlan plan) => string.Join('\n',
        plan.Files.Select(file => $"file|{file.Path}|{file.BasePath}|{file.Change}|{file.RequiresProjectExpansion}|" +
            string.Join(';', file.Removals.Select(removal => removal.Id)) + "|" +
            string.Join(';', file.Reasons.Select(reason => $"{reason.Code}:{reason.Message}")))
        .Concat(plan.Exclusions.Select(item =>
            $"exclude|{item.Path}|{item.ReasonCode}|{item.Overridden}|{item.Message}"))
        .Concat(plan.ProjectUnits.Select(unit =>
            $"unit|{unit.Project}|{unit.Expansion}|{string.Join(',', unit.Inputs)}"))
        .Concat(plan.Reasons.Select(reason => $"reason|{reason.Code}|{reason.Message}")));

    public void Dispose() => _repository.Dispose();
}
