namespace Mutate4CSharp.Tests;

public sealed class ScopeRoundThreeRegressionTests : IDisposable
{
    private readonly SnapshotTestRepository _repository = new();

    [Fact]
    public async Task InPlaceProductionToGeneratedTransitionRetainsBaseRemovalObligation()
    {
        PrepareConfiguredRepository("src/App/Subject.cs", "class Subject { int Value() => 1; }\n");
        _repository.WriteText("src/App/Subject.cs",
            "// <auto-generated/>\nclass Subject { int Value() => 2; }\n");

        var first = await PlanGitAsync();
        var second = await PlanGitAsync();

        AssertTransition(first, "src/App/Subject.cs", "GENERATED_SOURCE");
        Assert.Equal(PlanValue(first), PlanValue(second));
        AssertPublishable(first, "in-place-production-to-generated");
    }

    [Fact]
    public async Task RenamedProductionToTestTransitionRetainsBaseRemovalObligation()
    {
        PrepareConfiguredRepository("src/App/Subject.cs", "class Subject { int Value() => 1; }\n");
        _repository.Git("mv", "src/App/Subject.cs", "tests/App.Tests/Subject.cs");

        var plan = await PlanGitAsync();

        AssertTransition(plan, "tests/App.Tests/Subject.cs", "TEST_SOURCE");
        AssertPublishable(plan, "renamed-production-to-test");
    }

    [Fact]
    public async Task FileGeneratedOnBothSidesDoesNotInventBaseRemovalObligation()
    {
        PrepareConfiguredRepository("src/App/Generated.cs",
            "// <auto-generated/>\nclass Generated { int Value() => 1; }\n");
        _repository.WriteText("src/App/Generated.cs",
            "// <auto-generated/>\nclass Generated { int Value() => 2; }\n");

        var plan = await PlanGitAsync();

        Assert.Contains(plan.Exclusions, item => item.Path == "src/App/Generated.cs" &&
            item.ReasonCode == "GENERATED_SOURCE" && !item.Overridden);
        Assert.DoesNotContain(plan.Reasons, reason => reason.Code == "COMPILE_ITEM_REMOVED");
        Assert.Empty(plan.Files);
        Assert.Empty(plan.ProjectUnits);
        Assert.Contains(plan.Reasons, reason => reason.Code == "NO_APPLICABLE_PRODUCTION_CHANGES");
        Assert.True(plan.IsComplete);
        AssertPublishable(plan, "generated-on-both-sides");
    }

    [Fact]
    public async Task FileTestOnBothSidesUsesTestExpansionWithoutInventingBaseRemovalObligation()
    {
        PrepareConfiguredRepository("tests/App.Tests/Behavior.cs",
            "class Behavior { int Value() => 1; }\n");
        _repository.WriteText("tests/App.Tests/Behavior.cs", "class Behavior { int Value() => 2; }\n");

        var plan = await PlanGitAsync();

        Assert.Contains(plan.Exclusions, item => item.Path == "tests/App.Tests/Behavior.cs" &&
            item.ReasonCode == "TEST_SOURCE" && !item.Overridden);
        Assert.DoesNotContain(plan.Reasons, reason => reason.Code == "COMPILE_ITEM_REMOVED");
        Assert.Contains(plan.ProjectUnits, unit => unit.Project == "src/App/App.csproj" &&
            unit.Expansion == "FULL_PROJECT");
        Assert.DoesNotContain(plan.Reasons, reason => reason.Code == "NO_APPLICABLE_PRODUCTION_CHANGES");
        Assert.True(plan.IsComplete);
        AssertPublishable(plan, "test-on-both-sides");
    }

    [Fact]
    public async Task OverriddenInPlaceGeneratedTransitionRemainsAdmitted()
    {
        PrepareConfiguredRepository("src/App/Subject.cs", "class Subject { int Value() => 1; }\n",
            includeGenerated: true);
        _repository.WriteText("src/App/Subject.cs",
            "// <auto-generated/>\nclass Subject { int Value() => 2; }\n");

        var plan = await PlanGitAsync();

        Assert.Contains(plan.Exclusions, item => item.Path == "src/App/Subject.cs" &&
            item.ReasonCode == "GENERATED_SOURCE" && item.Overridden);
        Assert.Contains(plan.Files, file => file.Path == "src/App/Subject.cs" &&
            file.Declarations.Count > 0);
        Assert.DoesNotContain(plan.Reasons, reason => reason.Code == "COMPILE_ITEM_REMOVED");
        Assert.DoesNotContain(plan.Reasons, reason => reason.Code == "NO_APPLICABLE_PRODUCTION_CHANGES");
        AssertPublishable(plan, "overridden-generated-transition");
    }

    private void PrepareConfiguredRepository(string sourcePath, string source,
        bool includeGenerated = false)
    {
        _repository.WriteText("src/App/App.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\" />\n");
        _repository.WriteText("tests/App.Tests/App.Tests.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk\" />\n");
        _repository.WriteText(sourcePath, source);
        _repository.WriteText("mutate4csharp.json", $$"""
            { "version": 1, "includeGenerated": {{includeGenerated.ToString().ToLowerInvariant()}},
              "projects": [
              { "project": "src/App/App.csproj", "tests": ["tests/App.Tests/App.Tests.csproj"] }
            ] }
            """);
        _repository.Git("add", ".");
        _repository.Git("commit", "-m", "base");
    }

    private async Task<ScopePlan> PlanGitAsync()
    {
        await using var snapshot = await SnapshotCapture.CaptureAsync(_repository.Root, "HEAD", [],
            SnapshotCaptureOptions.Default, CancellationToken.None);
        return await ScopePlanner.PlanGitAsync(snapshot, CancellationToken.None);
    }

    private static void AssertTransition(ScopePlan plan, string currentPath, string exclusionCode)
    {
        Assert.Contains(plan.Exclusions, item => item.Path == currentPath &&
            item.ReasonCode == exclusionCode && !item.Overridden);
        var file = Assert.Single(plan.Files, item => item.Path == currentPath);
        Assert.True(file.RequiresProjectExpansion);
        Assert.Contains(file.Reasons, reason => reason.Code == "COMPILE_ITEM_REMOVED");
        Assert.Contains(plan.Reasons, reason => reason.Code == "COMPILE_ITEM_REMOVED");
        Assert.Contains(plan.ProjectUnits, unit => unit.Project == "src/App/App.csproj" &&
            unit.Expansion == "FULL_PROJECT" && unit.Inputs.Contains("src/App/Subject.cs"));
        Assert.DoesNotContain(plan.Reasons, reason => reason.Code == "NO_APPLICABLE_PRODUCTION_CHANGES");
        Assert.True(plan.IsComplete);
    }

    private static void AssertPublishable(ScopePlan plan, string runId)
    {
        var report = EvaluationReport.CreateSynthetic(EvaluationOutcome.Incomplete, runId, "TEST_FIXTURE")
            with { ScopePlan = plan, Selection = new("base", "HEAD", []) };
        Assert.NotEmpty(ReportWriter.Serialize(report));
    }

    private static string PlanValue(ScopePlan plan) => string.Join('\n',
        plan.Files.Select(file => $"file|{file.Path}|{file.BasePath}|{file.Change}|{file.RequiresProjectExpansion}|" +
            string.Join(';', file.Reasons.Select(reason => $"{reason.Code}:{reason.Message}")))
        .Concat(plan.Exclusions.Select(item =>
            $"exclude|{item.Path}|{item.ReasonCode}|{item.Overridden}|{item.Message}"))
        .Concat(plan.ProjectUnits.Select(unit =>
            $"unit|{unit.Project}|{unit.Expansion}|{string.Join(',', unit.Inputs)}"))
        .Concat(plan.Reasons.Select(reason => $"reason|{reason.Code}|{reason.Message}")));

    public void Dispose() => _repository.Dispose();
}
